k8s_namespace: "example"
directorio_trabajo: "/tmp"
aplicacion:
  definicion: "stateless.yaml"
  backend:
    nombre: app-back 
    imagen: acrdevopspablo.azurecr.io/redis:casopractico2
    replicas: 1
    recursos:
      cpu: 100m
      memoria: 128Mi
    limites:
      cpu: 250m
      memoria: 256Mi
    puerto: 6379
  frontend:
    nombre: app-front
    imagen: acrdevopspablo.azurecr.io/front:casopractico2
    replicas: 1
    recursos:
      cpu: 100m
      memoria: 128Mi
    limites:
      cpu: 250m
      memoria: 256Mi
    puerto: 80

