---
- name: 'Podman'
  hosts: webservers
  remote_user: adminUsername
  become: true
  vars_files:
    - vars/01_vars.yaml

  tasks:
    - name: 'Instalar Podman y resto de componentes'
      command: sudo dnf -y install podman httpd-tools openssl

    - name: 'Creamos un directorio para nuestra aplicación Web'
      command: mkdir webserver
      ignore_errors: True
         
    - name: 'Creamos un fichero para nuestra BBDD de usuarios que se puedan autenticar en nuestra aplicación Web'
      command: htpasswd -cBb ./webserver/.creds test D3v0ps.2023

    - name: 'Creación de clave para generar Certificado autofirmado'
      command: openssl genrsa -out ./webserver/localhost.key 2048

    - name: 'Solicitud del Certificado'
      command: openssl req -key ./webserver/localhost.key -new -out ./webserver/localhost.csr -subj "/C=ES/ST=Madrid/L=Madrid/O=DevOps/OU=Ejemplo/CN=vml"

    - name: 'Generamos el Certificado'
      command: openssl x509 -signkey ./webserver/localhost.key -in ./webserver/localhost.csr -req -days 365 -out ./webserver/localhost.crt
     
    - name: 'Copiamos el fihero httpd'
      ansible.builtin.copy:
        src: configFiles/httpd.conf
        dest: ./webserver
        mode: '0644'

    - name: 'Copiamos el fihero .htaccess'
      ansible.builtin.copy:
        src: configFiles/.htaccess
        dest: ./webserver
        mode: '0644'   

    - name: 'Copiamos el fihero index'
      ansible.builtin.copy:
        src: configFiles/index.html
        dest: ./webserver
        mode: '0644'

    - name: 'Copiamos el fihero de la imagen del contenedor'
      ansible.builtin.copy:
        src: configFiles/Containerfile
        dest: ./webserver
        mode: '0644'
        
    - name: 'Generamos nuestra imagen de contenedor'
      command: sudo podman build -t webserver ./webserver

    - name: 'Etiquetamos la imagen para subirla a ACR '
      command: sudo podman tag localhost/webserver:latest acrdevopspablo.azurecr.io/webserver:casopractico2    
        
