---
- name: 'aks'
  hosts: localhost
  become: true
  vars_files:
    - vars/02_vars.yaml
    
  tasks: 

  # Falta subir las images a nuesto acr para poder modificar las variables y que la coja de ahi
  # para subirla usamos un metodo de ansible
  
    - name: 'Definir los objectos deployment y servicios'
      ansible.builtin.template:
       src: templates/stateless.j2
      dest: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"
        
   - name: 'Crear namespace'
     kubernetes.core.k8s:
        kind: Namespace
        name: "{{ k8s_namespace}}"
      ignore_errors: True   

    - name: 'Crear Deployments y servicios de la aplicación'
      kubernetes.core.k8s:
       state: present
       template: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"
