---
- name: 'acr'
  hosts: webservers
  remote_user: adminUsername
  become: true

  tasks:

   - name: 'Descargamos imagen que subiremos posteriormente a nuestro ACR'
     containers.podman.podman_image:
       name: mcr.microsoft.com/oss/bitnami/redis
       tag: 6.0.8
