---
- name: 'aks'
  hosts: localhost
  become: true
  vars_files:
    - vars/02_vars.yaml
    
  tasks: 

    - name: 'Credenciales AZ'
      command: sudo az aks get-credentials --resource-group kubernetes_rg --name cluster --overwrite-existing
  
    - name: 'Definir los objectos deployment y servicios'
      ansible.builtin.template:
       src: templates/stateless.j2
       dest: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"
    
    - name: 'Crear espacio de nombres'
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ k8s_namespace}}"
        
    - name: 'Crear Deployments y servicios de la aplicación'
      kubernetes.core.k8s:
       state: present
       template: "{{ directorio_trabajo }}/{{ aplicacion.definicion }}"

    - name: 'Comprobamos los deployments del nuevo namespace'
      command: sudo kubectl get deployment -n example
      register: dep

    - name: 'Comprobamos los Servicios'
      command: sudo kubectl get svc -n example
      register: sc

    - name: 'Mostramos los deployments'
      debug:
        msg: "Ansible Version: {{ dep.stdout }}"

     - name: 'Mostramos los Servicios'
       debug:
         msg: "Ansible Version: {{ sc.stdout }}"
